apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster-auth
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: togglemaster
type: Opaque
stringData:
  MASTER_KEY: change-me